blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/mcanouil/quarto-extensions-updater/discussions
    about: Please ask and answer questions here.
  - name: Issue with Quarto CLI
    url: https://github.com/quarto-dev/quarto-cli
    about: Please report issues with the Quarto CLI here
  - name: Issue with Quarto Wizard
    url: https://github.com/mcanouil/quarto-wizard
    about: Please report issues with the Quarto Wizard here.
